# Generated by Django 4.2.16 on 2024-09-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirdFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default title', max_length=200)),
                ('title', models.CharField(default='default title', max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age_of_the_animal', models.CharField(max_length=200)),
                ('animal_size', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(max_length=200, null=True, upload_to='images/')),
                ('link', models.CharField(default='default title', max_length=1000)),
                ('image_link', models.CharField(default='default title', max_length=1000)),
                ('description', models.CharField(default='default title', max_length=5000)),
                ('manufacturer', models.CharField(default='', max_length=200)),
                ('sale', models.BooleanField(default=False)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default title', max_length=200)),
                ('title', models.CharField(default='default title', max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age_of_the_animal', models.CharField(max_length=200)),
                ('animal_size', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(max_length=200, null=True, upload_to='images/')),
                ('link', models.CharField(default='default title', max_length=1000)),
                ('image_link', models.CharField(default='default title', max_length=1000)),
                ('description', models.CharField(default='default title', max_length=5000)),
                ('manufacturer', models.CharField(default='', max_length=200)),
                ('sale', models.BooleanField(default=False)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DogFoodDry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default title', max_length=200)),
                ('title', models.CharField(default='default title', max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age_of_the_animal', models.CharField(max_length=200)),
                ('animal_size', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(max_length=200, null=True, upload_to='images/')),
                ('link', models.CharField(default='default title', max_length=1000)),
                ('image_link', models.CharField(default='default title', max_length=1000)),
                ('description', models.CharField(default='default title', max_length=5000)),
                ('manufacturer', models.CharField(default='', max_length=200)),
                ('sale', models.BooleanField(default=False)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
