# Generated by Django 5.1.1 on 2024-09-22 07:22

import zoo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdfood',
            name='id_image',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='birdfood',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to=zoo_app.models.get_clinic_image_path),
        ),
    ]
