# Generated by Django 5.1.1 on 2024-09-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0002_birdfood_id_image_alter_birdfood_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catfood',
            name='id_image',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dogfooddry',
            name='id_image',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
