# Generated by Django 5.1.1 on 2024-09-22 08:02

import zoo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0003_catfood_id_image_dogfooddry_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catfood',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to=zoo_app.models.get_clinic_image_path),
        ),
        migrations.AlterField(
            model_name='catfood',
            name='image_link',
            field=models.CharField(default='default title', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dogfooddry',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to=zoo_app.models.get_clinic_image_path),
        ),
    ]
