# Generated by Django 5.1.1 on 2024-09-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0005_alter_catfood_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catfood',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
