# Generated by Django 5.1.1 on 2024-10-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
